name: dartserverplayground
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: perfect <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2

#dev_dependencies:
#  test: ^1.0.0

dev_dependencies:
  build_runner: ^1.0.0
#  build_test: ^0.10.3
  build_web_compilers: ^0.4.4